const fs = require('fs');
const file = 'c:\\\\Users\\\\Henri\\\\Documents\\\\Programação\\\\Haumea Studies\\\\lib\\\\math-generators.ts';
let p = fs.readFileSync(file, 'utf8');

const replacements = {
    'Ã lgebra': 'Álgebra',
    'GeraÃ§Ã£o': 'Geração',
    'questÃµes': 'questões',
    'matemÃ¡ticas': 'matemáticas',
    'ResoluÃ§Ã£o': 'Resolução',
    'mÃºltipla': 'múltipla',
    'FatoraÃ§Ã£o': 'Fatoração',
    'expressÃµes': 'expressões',
    'algÃ©bricas': 'algébricas',
    'PotenciaÃ§Ã£o': 'Potenciação',
    'potÃªncias': 'potências',
    'RacionalizaÃ§Ã£o': 'Racionalização',
    'FraÃ§Ãµes': 'Frações',
    'OperaÃ§Ãµes': 'Operações',
    'EquaÃ§Ãµes': 'Equações',
    '1Âº': '1º',
    '2Âº': '2º',
    'quadrÃ¡ticas': 'quadráticas',
    'ProgressÃµes': 'Progressões',
    'aritmÃ©ticas': 'aritméticas',
    'geomÃ©tricas': 'geométricas',
    'FunÃ§Ãµes': 'Funções',
    'DomÃ­nio': 'Domínio',
    'composiÃ§Ã£o': 'composição',
    'AnÃ¡lise': 'Análise',
    'Ã¢ngulos': 'ângulos',
    'notÃ¡veis': 'notáveis',
    'NotaÃ§Ã£o': 'Notação',
    'CientÃ­fica': 'Científica',
    'ConversÃ£o': 'Conversão',
    'fÃ­sicas': 'físicas',
    'AnalÃ­tica': 'Analítica',
    'DistÃ¢ncia': 'Distância',
    'circunferÃªncia': 'circunferência',
    'EstatÃ­stica': 'Estatística',
    'cÃ¡lculo': 'cálculo',
    'CombinatÃ³ria': 'Combinatória',
    'combinaÃ§Ã£o': 'combinação',
    'permutaÃ§Ã£o': 'permutação',
    'MÃ©dia': 'Média',
    'âˆš': '√',
    'Î”': 'Δ',
    'Â±': '±',
    'Â²': '²',
    'Â³': '³',
    'diferenÃ§a': 'diferença',
    'trinÃ´mio': 'trinômio',
    'DivisÃ£o': 'Divisão',
    'nÃ£o': 'não',
    'fÃ³rmula': 'fórmula',
    'fraÃ§Ã£o': 'fração',
    'fraÃ§Ãµes': 'frações',
    'Pitagoras': 'Pitágoras',
    'perimetros': 'perímetros',
    'Areas': 'Áreas',
    'solidos': 'sólidos',
    'area': 'área',
    'potÃªncia': 'potência',
    'entÃ£o': 'então',
    'Ã¡': 'á',
    'Ã¢': 'â',
    'Ã£': 'ã',
    'Ã©': 'é',
    'Ãª': 'ê',
    'Ã­': 'í',
    'Ã³': 'ó',
    'Ã´': 'ô',
    'Ãµ': 'õ',
    'Ãº': 'ú',
    'Ã§': 'ç'
};

let fixed = p;
for (const [k, v] of Object.entries(replacements)) {
    fixed = fixed.split(k).join(v);
}

fs.writeFileSync(file, fixed, 'utf8');
console.log('Fixed encoding issues');
